// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjHmK15pbHpOvmJvXh7OpE42d8tnh1REY',
    appId: '1:155365281335:web:6fb1a20acb69480df8b9b2',
    messagingSenderId: '155365281335',
    projectId: 'sample-firebase-ai-app-bdd63',
    authDomain: 'sample-firebase-ai-app-bdd63.firebaseapp.com',
    databaseURL: 'https://sample-firebase-ai-app-bdd63-default-rtdb.firebaseio.com',
    storageBucket: 'sample-firebase-ai-app-bdd63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHERap5iSSd1nakiX2W2iDMVms29NQMnA',
    appId: '1:155365281335:android:cab975369ba5788cf8b9b2',
    messagingSenderId: '155365281335',
    projectId: 'sample-firebase-ai-app-bdd63',
    databaseURL: 'https://sample-firebase-ai-app-bdd63-default-rtdb.firebaseio.com',
    storageBucket: 'sample-firebase-ai-app-bdd63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx9CxKeImWKN87AZ_3QOcnno3ArN2fNik',
    appId: '1:155365281335:ios:b0f678d059171f79f8b9b2',
    messagingSenderId: '155365281335',
    projectId: 'sample-firebase-ai-app-bdd63',
    databaseURL: 'https://sample-firebase-ai-app-bdd63-default-rtdb.firebaseio.com',
    storageBucket: 'sample-firebase-ai-app-bdd63.firebasestorage.app',
    iosBundleId: 'com.example.tecksaleQuanlybanhang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjHmK15pbHpOvmJvXh7OpE42d8tnh1REY',
    appId: '1:155365281335:web:7279e454675c2762f8b9b2',
    messagingSenderId: '155365281335',
    projectId: 'sample-firebase-ai-app-bdd63',
    authDomain: 'sample-firebase-ai-app-bdd63.firebaseapp.com',
    databaseURL: 'https://sample-firebase-ai-app-bdd63-default-rtdb.firebaseio.com',
    storageBucket: 'sample-firebase-ai-app-bdd63.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx9CxKeImWKN87AZ_3QOcnno3ArN2fNik',
    appId: '1:155365281335:ios:b0f678d059171f79f8b9b2',
    messagingSenderId: '155365281335',
    projectId: 'sample-firebase-ai-app-bdd63',
    databaseURL: 'https://sample-firebase-ai-app-bdd63-default-rtdb.firebaseio.com',
    storageBucket: 'sample-firebase-ai-app-bdd63.firebasestorage.app',
    iosBundleId: 'com.example.tecksaleQuanlybanhang',
  );

}